# Generated by Django 6.0.5 on 2026-06-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='starts',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
