# Generated by Django 6.0.5 on 2026-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_starts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='starts',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
